### ISSUE TITLE
Upload .webm files

### ISSUE THREAD

**Issue by jjnilton** [markasoftware/gif-is-jif#1]
Is it supposed to work with .webm files too?

Tried to upload a .webm file, from the program output it says that upload is complete but it seems it wasn't processed by gfycat.

```
$ ./upload.bash ~/Videos/Screencast_11-01-2017_11\:35\:59.webm 
Getting gfycat key and name...
About to upload. This might take a while.
There will be no indication of progress until it's complete.
Upload complete. Your gif will be at https://gfycat.com/ValuableSlimyBangeltiger
It won't show up yet because Gfycat takes a couple minutes to process the gif
```

**Comment by markasoftware** [comment]
Ok, I think i have resolved this issue. The issue is not with `.webm`s specifically, it's that Gfycat now automatically detects duplicate uploads, and when it did this the url my script outputted would be incorrect. This should be resolved now, let me know if it works!
